services:
    _instanceof:
        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ['setContainer', ['@service_container']]
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Trilobit\JointformsBundle\Controller\ContentElement\NavigationController: ~
    Trilobit\JointformsBundle\Controller\ContentElement\FormController: ~
    Trilobit\JointformsBundle\Controller\ContentElement\SummaryController: ~
    Trilobit\JointformsBundle\Controller\ContentElement\RedirectController: ~
    Trilobit\JointformsBundle\EventListener\CompileFormFieldsListener: ~
    Trilobit\JointformsBundle\EventListener\LoadFormFieldListener: ~
    Trilobit\JointformsBundle\EventListener\ParseFrontendTemplateListener: ~

    Trilobit\JointformsBundle\DataProvider\Configuration\ConfigurationProvider: ~

    Trilobit\JointformsBundle\EventListener\ProcessFormDataListener:
        public: true
        arguments:
            - '@event_dispatcher'
